### ISSUE TITLE
Reconsider using the GNU Affero for it

### ISSUE THREAD

**Issue by mudrd8mz** [mebis-lp/mod_learningmap#10]
I generally discourage from using AGPL for Moodle plugins. Even though I like the idea and the spirit of the license, and I appreciate the intention to use it in Moodle plugins, there is a narrow grey zone - see the second paragraph at https://www.gnu.org/licenses/license-list.en.html#AGPL

It is recommended that the plugins as packages are under GPLv3 - basically as a consequence of being part of Moodle which itself is GPLv3. Plugins may contain 3rd party libraries if they are compatible with GPLv3. So it is OK if the plugin ships with a library under AGPL, but it works better if the plugin itself is under GPL.

This is not an approval blocker, just something to re-consider maybe.

**Comment by sh-csg** [comment]
License will be changed in next release!
