### ISSUE TITLE
Bug: When using assignments and automatic back links in learning maps attached files are hidden

### ISSUE THREAD

**Issue by babicht** [mebis-lp/mod_learningmap#102]
Hey :)

We found some kind of strange behavior when using assignments in learning maps. If you add a file via "intro attachments" and add the assignment to a learning map, everything works fine. Students can see the files and navigate the learning map. But as soon as you enable the automatic back links those files are gone. Students can't see those files and instead there is only the back link visible. Kind of like it's overwriting the file display.

Before enabling back links:
![image](https://github.com/mebis-lp/mod_learningmap/assets/136691601/498a32e3-eac2-4088-b19f-6dc8f30d928b)

After enabling back links:
![image](https://github.com/mebis-lp/mod_learningmap/assets/136691601/18f3da01-2ec8-4ea0-9c42-02027b9b80fd)

Thanks for your help!

Plugin version: 0.9.7 (2024022102)
Moodle version: 4.1.9

**Comment by sh-csg** [comment]
This will be fixed by #103
