### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by mattgig** [mebis-lp/mod_learningmap#11]
When I try to install the plugin in Moodle 3.11.6, my instance throws the following error:

Warning: is_readable(): open_basedir restriction in effect. File(/db/renamedclasses.php) is not within the allowed path(s): (/home/httpd/vhosts/learn4school.ch/:/tmp/) in /home/httpd/vhosts/.../httpsdocs/.../lib/classes/component.php on line 1210 

Is it possible that plugin assumes that Moodle should be installed in a /moodle/ directory?

**Comment by sh-csg** [comment]
Can you please provide some steps to reproduce the error?

I don't see any files of our plugin involved in the error description, so I'm not sure if this is a bug in mod_learningmap.

A similiar problem is described [here](https://moodle.org/mod/forum/discuss.php?d=425424).

**Comment by mattgig** [comment]
You are right, I changed the PHP version recently which caused the error when upgrading plugins. There is no connection to your plugin. Thanks for the workaround.
