### ISSUE TITLE
Option for "Pulse animation for unvisited places" does not run as expected

### ISSUE THREAD

**Issue by benutzer-prog** [mebis-lp/mod_learningmap#112]
I am using the latest version of Moodle 4.1.13. The above option does not work in the following scenario:

I have a top map that links to sub maps, which in turn can also be visited. Despite the activity setting of the sub maps, it is not marked as visited ("like somebody just clicked on it", I have to complete it first, so that the animation for unvisited places no longer plays. I have understood the option “Pulse animation for unvisited places” to mean that, regardless of the completion settings, the status of this element changes to “visited” as soon as I have called up the activity.

Here are my steps to reproduce the behavior:
- create two learning maps
- link from one map to the second map
- set the completion setting on the second map to “the user have to open it” and also “the user have to reach one target”
- set the option on the second map “Pulse animation for unvisited places” checked
- open the second map over the marker on the first map
-> the result is that even if I “visited” the second map the marker on the first map stays on the pulse animation.

Was that the intention of this option? Is it possible to check the first completion option “the user have to open the activity” and set the marker to visited to lose the pulse animation class, but keep it uncompleted till every completion setting is fulfilled?

Kind regards and many thanks for this amazing plugin,

Ben

Translated with DeepL.com (free version)

**Comment by sh-csg** [comment]
Thanks a lot for pointing this out. This might be a problem with the use of "visited" in context of learning maps: "visited" means the same as "completed" (depending of the completion criteria of the activity).
