### ISSUE TITLE
Feature request: Improve live updating of learning map

### ISSUE THREAD

**Issue by PhMemmel** [mebis-lp/mod_learningmap#26]
The JS module `manual-completion-watch` tries to query all manual completion buttons of all visible course modules to update the learning map.

After implementing group mode (see #25) one student needs to reload the learningmap whenever another student has completed a task to continue working on the learning map. A nice feature would be to rework the module `manual-completion-watch` and make use of the new state manager of the course editor API. This way the learning map also updates if activities are being completed in another tab or - in case of group mode - as soon as another student is completing an activity (no matter if manually or by fulfilling a condition).

The old way with the `manual-completion-watch` module should still be kept for backwards compatibility reasons (moodle 3.11 and below) for a while I think.

Caveat: It could be pretty bad if updating the learning map is being done by reloading the page. If a student completes an activity another student should not have reloaded the page, but the learning map should be updated. Maybe just use a notification popup "The status of activities on the learning map has been changed. Please reload the page to update the learningmap"?

**Comment by sh-csg** [comment]
This is partly resolved by #48
