### ISSUE TITLE
Bug: Moodle 4.0 shows learning map twice

### ISSUE THREAD

**Issue by PhMemmel** [mebis-lp/mod_learningmap#28]
To reproduce:

Disable "Show map on course page", click on the module link to see the view page, you will see it twice:

Once without places and paths, right below with places and paths.

Tested on moodle 4.1dev (Build: 20220701), boost theme

![grafik](https://user-images.githubusercontent.com/65113153/180619308-6dd76c6a-41c9-4c64-932f-a66b6d7e4b0e.png)

Also the map always takes all the space available. Here a max-width attribute should be added, because in some cases it's not even possible to see the map as a whole. Zooming in and out in the browser even makes it worse / the map take even more space relative to everything else.

I had to popup the drawers left and right and then shrink the browser window to be able to at least get this screenshot.

**Comment by sh-csg** [comment]
Bug is resolved by [93226e8](https://github.com/mebis-lp/mod_learningmap/commit/93226e88526fa8e943c14f8867807609571ed327)
