### ISSUE TITLE
Maintenance: Unit tests needed for availability of places/paths

### ISSUE THREAD

**Issue by PhMemmel** [mebis-lp/mod_learningmap#33]
Especially the features "Show all places" (#24) and "Group mode" (#25) are increasing the complexity of when an activity is being shown and/or accessible to a user by a lot.

There should be extensive unit tests to test if an activity is visible and accessible by a user depending on:
- which group the user is member of and which group currently is being selected by the user in group mode
- moodle core availability restrictions (e. g. restrict access by date, activity completion of another activity etc.)
- "show all" mode of the learningmap
- edit mode of the trainer

We also need a test that tests if the completion modes are working properly, especially in group mode. Care: Moodle seems to have issues here with caching.

Eventually there also should be the corresponding tests for path visibility including the "hide paths" feature.

**Comment by PhMemmel** [comment]
Actually there are quite a lot of new features increasing complexity. So probably it would be good to cover as much of the functionality by behat tests

**Comment by sh-csg** [comment]
Thanks a lot for your suggestion! Unit and acceptance tests are on the roadmap for version 1.0.

**Comment by ug-lisa-lsa** [comment]
Re: moodle core availability restrictions

We recently updated to v0.9.3. Today a teacher reported that previously working scenario of restricting access to an acitivity with a password and using this activity in a learning map isn't working anymore. Was able to reproduce the current issue but can't say if it ever actually worked. Currently the learning place (red dot on the map) can't be selected or clicked if access to the corresponding activity is restricted by password.
