### ISSUE TITLE
Moodle 3.9 Error Class 'core_completion\activity_custom_completion' not found

### ISSUE THREAD

**Issue by eledia** [mebis-lp/mod_learningmap#34]
There is always a dependency on a higher version of Moodle, so all the versions will not run in 3.9. Can you please fix this problem?

/mod/learningmap/classes/completion/custom_completion.php

line 29: class custom_completion extends **\core_completion\activity_custom_completion** {

Error: **Class 'core_completion\activity_custom_completion' not found**

×Debug-Info: 
Error code: generalexceptionmessage
×Stack trace: 
**line 29 of /mod/learningmap/classes/completion/custom_completion.php: Error thrown**
line 132 of /lib/classes/component.php: call to include_once()
line ? of unknownfile: call to core_component::classloader()
line 162 of /mod/learningmap/mod_form.php: call to spl_autoload_call()
line 757 of /course/moodleform_mod.php: call to mod_learningmap_mod_form->add_completion_rules()
line 126 of /mod/learningmap/mod_form.php: call to moodleform_mod->standard_coursemodule_elements()
line 214 of /lib/formslib.php: call to mod_learningmap_mod_form->definition()
line 130 of /course/moodleform_mod.php: call to moodleform->__construct()
line 150 of /course/modedit.php: call to moodleform_mod->__construct()

**Comment by xmontana** [comment]
Hello, same issue with Moodle 3.10.11

**Comment by jdmagnore** [comment]
Any update? Thanks in advance.

**Comment by sh-csg** [comment]
Thanks a lot for reporting the issue! We will provide a separate branch for moodle 3.9 / 3.10 as soon as it's ready.
Please be aware that we will drop support for moodle 3.9 / 3.10 at some point (there is no date for this yet).
