### ISSUE TITLE
Error code when “Show map on course page” disabled

### ISSUE THREAD

**Issue by judithschittenkopf** [mebis-lp/mod_learningmap#56]
When “Show map on course page” is disabled in the settings of a learning map activity, the learning map icon appears on the course page and can be clicked as well. When clicked, a page opens. The page, however, does not show the learning map. Instead, it says, “Coding error detected, it must be fixed by a programmer: Unknown property activityheader of $PAGE.” Returning into the settings and enabling "Show map on course page" again is still possible.
This is on moodle 3.11.5

**Comment by sh-csg** [comment]
Thanks a lot for the bug report. This will be fixed by #57 .
