### ISSUE TITLE
Getting error when using in separate page mode

### ISSUE THREAD

**Issue by farazandeh** [mebis-lp/mod_learningmap#64]
Hello team and thank you for this cool practical plugin.
We're using moodle 3.10 & when we try to use the map on separate page, we get an error:

Coding error detected, it must be fixed by a programmer: Unknown property activityheader of $PAGE.
line 832 of /lib/pagelib.php: coding_exception thrown
line 41 of /mod/learningmap/view.php: call to moodle_page->__get()

Can you please help with this issue? 🙌🏻

**Comment by PhMemmel** [comment]
This has already been fixed, see #56. Please update your plugin to the latest version and the error will be gone.
