### ISSUE TITLE
Call to undefined function mod_learningmap\array_remove_by_value

### ISSUE THREAD

**Issue by andremenrath** [mebis-lp/mod_learningmap#67]
Reported by:
https://bildung.social/@FrauBainski/109834002858374211

Possible solutions:
1. Probably the fallback to global namespace should be enforced in https://github.com/mebis-lp/mod_learningmap/blob/1f9f1274919ddd46c76b6237f7156540dde0cbf6/classes/mapworker.php#L308

2. Maybe it is better to replace this function by just changing the line to `array_values(array_diff($active, array($path['id'])));` cause array_remove_by_value has no phpdocs, proper type checks and so on.

**Comment by sh-csg** [comment]
Thanks for reporting! This is already fixed in v0.9.2
