### ISSUE TITLE
Bug:  array_remove_by_value(.) is missing

### ISSUE THREAD

**Issue by abkoch** [mebis-lp/mod_learningmap#69]
Dear Stefan,

function "array_remove_by_value(.)" is missing in `mod_learningmap 0.9 (build 2023011004)`. Could be fixed by including 

`include '../backup/cc/cc_lib/gral_lib/functions.php';
`

in `mapworker.php`. Or is this already fixed in `0.9.2`?

Used moodle versions: `4.0.6` and `4.0.7`.

Best regards
Andreas

**Comment by PhMemmel** [comment]
Thank you for reporting this issue. This has already been fixed in 0.9.2 (see #63). Please update mod_learningmap to the latest version.

**Comment by abkoch** [comment]
Great! Thanks for your immediate response.

Best regards
Andreas
