### ISSUE TITLE
Plugin uses GD extension with freetype enabled, but doesn't do required/optional in a environment.xml

### ISSUE THREAD

**Issue by danowar2k** [mebis-lp/mod_learningmap#73]
Moodle provides the ability to do an environment.xml where you describe which PHP version or PHP extensions your plugin needs.

Moodle core requires the GD extension, but doesn't check apart from "is this extension present". 

You use freetype only functions, namely `imagettfbbox()`: https://github.com/mebis-lp/mod_learningmap/blob/5ada8bc96d4963fe86d7bef94bdd138ec8b65c29/classes/mapworker.php#L261

Could you add an environment.xml with a "required" for GD and an "optional check" with a custom function checking if freetype is enabled?

It would help others to determine the requirements to use this plugin better.

Or you could just replace the function with something else ;-)

**Comment by danowar2k** [comment]
Relevant Moodle core issue: https://tracker.moodle.org/browse/MDL-58999

Issue in some other plugin we're using: https://github.com/jleyva/moodle-block_configurablereports/issues/233

**Comment by PhMemmel** [comment]
@danowar2k Would you mind testing the linked PR against the environment you experienced the issue?

**Comment by danowar2k** [comment]
Sorry had advisory absolutely no time to confirm this...
