### ISSUE TITLE
Fix wrong display location button "Group mode" in Moodle 4.3

### ISSUE THREAD

**Issue by tholudwig** [mebis-lp/mod_learningmap#88]
**Description**
With Moodle 4.3, new modal boxes have been added for the group mode.
For standard activities, such as Wiki, this is displayed to the left of the completion.
![groupemode_wiki](https://github.com/mebis-lp/mod_learningmap/assets/14368866/21efd8ff-8794-42b7-b856-33bc416af5b3)

For the learning map, the button appears left-aligned.
![groupmode_learningmap](https://github.com/mebis-lp/mod_learningmap/assets/14368866/ea7e8b07-f426-47d1-be7a-6d97ec15dd23)

**Goal**
1. the button should be displayed for a uniform UX as with the standard activities

**Testing**
1. create a course with activated group mode.
2. create a learning map with display on the course page
3. hover over the activities 
 * Before the fix: Button is displayed left-aligned
 * after the fix: button is rendered in the correct position

**Comment by sh-csg** [comment]
This is a bug in Moodle core, since activities that don't have a view page and support group mode at the same time are not considered there.
See https://tracker.moodle.org/browse/MDL-80716 for details.
