### ISSUE TITLE
Missing function name prefix

### ISSUE THREAD

**Issue by mudrd8mz** [mebis-lp/mod_learningmap#9]
Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

Functions like `get_learningmap()` or `get_place_cm()` are defined in the global space without the expected prefix and there is a potential for a name collision.

**Comment by sh-csg** [comment]
Thank you for pointing out this issue. It is fixed in v0.5 (currently in review).
