### ISSUE TITLE
Big Problem: Error reading the database after update to v.0.9.6

### ISSUE THREAD

**Issue by chschlegel** [mebis-lp/mod_learningmap#91]
Hello
I updated the plugin from v0.9.5.2 to v.0.9.6 on moodle version 4.1.8.
The learning map still appears in the course. None of the links work. Editing of the activity isn't possible.

There allway the same error:
Error reading the database

I hope you fix it soon...

![error](https://github.com/mebis-lp/mod_learningmap/assets/17317421/c9500b87-1f08-4d2d-bea1-e16e0b3255ba)

**Comment by PhMemmel** [comment]
Are you able to enable the debugging mode for your instance and share the error message including debugging information?

**Comment by chschlegel** [comment]
yes, of course. Debuging when I click on an path point:

Fehler
Fehler beim Lesen der Datenbank

Debug info: Unknown column 'backlink' in 'field list'
SELECT name, placestore, backlink FROM mdl_learningmap WHERE id = ?
-- line 1679 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
-- line 1372 of /lib/outputrenderers.php: call to learningmap_before_http_headers()
-- line 251 of /mod/quiz/view.php: call to core_renderer->header()
[array (
0 => '21',
)]
Error code: dmlreadexception
Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1282 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 1679 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
line 1651 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 349 of /mod/learningmap/lib.php: call to moodle_database->get_record()
line 1372 of /lib/outputrenderers.php: call to learningmap_before_http_headers()
line 251 of /mod/quiz/view.php: call to core_renderer->header()

**Comment by PhMemmel** [comment]
Thank you very much. Just to make sure: You have run an upgrade on the Moodle site, right?

**Comment by chschlegel** [comment]
> Thank you very much. Just to make sure: You have run an upgrade on the Moodle site, right?

no, I only updated the plugin. Nothing else changed.

**Comment by PhMemmel** [comment]
Thanks for the answer. I actually was talking about the fact if you just updated the code or also ran the upgrade procedure of moodle which you probably did. The fix is now merged, a new version including the fix will be released soon.

Thank you very much for your quick report which made it possible for us to provide a quick fix before many more people stumble over this bug.

**Comment by chschlegel** [comment]
Thanks a lot for the quick fix. It worked on my test site and our development server.
Have a great weekend!
